### ISSUE TITLE
Naming experiments

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#101]
Now that we have "experiments", "surveys" and "games", it seems like we might want to change our general use word "Experiment".

For instance, on the docker it should probably say "Available Tasks". Same thing for the data - one column is "Experiment", but maybe we want to change that to "Task".

Also, currently in the data there is not necessarily a way to distinguish surveys, games and experiments. Could we enforce that all surveys end with "_survey", games end with "_game", or something like that?

**Comment by vsoch** [comment]
We actually don't need to distinguish surveys, experiments, or games with a requirement on the unique id - the only reason that I added "_survey" to the surveys is because the identical ones exist in experiments. The distinguishing feature is the repo that the experiment comes from, and the template variable that always is carried with the config.json. When you are happy with the surveys, it would be great to delete them in expfactory-experiments, and in fact I would do this one by one as you test and confirm that everything is working (as we know there are some remaining issues with validation of particular questions) and until those are resolved, the jspsych version can be used.

The data distinguishes by way of the template variable in config.json. Each template is associated with one of "surveys" "experiments" or "games" and this determines both the install folder, and how the task is rendered. I agree on Docker we should say available tasks, and I will change this promptly. I will also add a column to the various tables to distinguish "experiment" or "survey" or "game".

For the data export, this should not be further developed because it's going to be replaced to use the API to generate tab delimited data, and actually users should be encouraged to use expanalysis to generate specific parsings of the json data. Right now it's a big "hard coded" and this is just not going to work.
