### ISSUE TITLE
create view to find workers that have not submit, and time has run out

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-docker#142]

**Comment by vsoch** [comment]
![image](https://cloud.githubusercontent.com/assets/814322/15082653/dd0ef2b2-137d-11e6-9e82-616782300d00.png)

**Comment by IanEisenberg** [comment]
Very nice!

On Fri, May 6, 2016 at 11:30 AM, Vanessa Sochat <notifications@github.com>
wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/814322/15082653/dd0ef2b2-137d-11e6-9e82-616782300d00.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-docker/issues/142#issuecomment-217522850>
>



-- 
Best,
Ian

**Comment by vsoch** [comment]
added to battery details view, also simplified the viewing of HITS

![image](https://cloud.githubusercontent.com/assets/814322/15082863/e26161fe-137e-11e6-820b-643427d7a8ff.png)

**Comment by IanEisenberg** [comment]
It's a little confusing that "Manage HIT" takes you to a worker panel that
gives you access to all HITs. It'd be better if clicking "Manage HIT"
subset the workers by the HIT ID, and there was a separate battery level
"Manage battery" that displayed worker status across all HITs. The redesign
looks nice!

**Comment by vsoch** [comment]
I intended for manage hit to only be specific to the HIT - looks like I just forgot to add the filter when I started working on the template! One sec.

**Comment by vsoch** [comment]
ok check it out now, just fixed!

**Comment by IanEisenberg** [comment]
Cool, looks very nice. Considering that most people will be just making repeated HITs for one battery, it still probably would make sense to have a "manage workers across battery"

One oddity: Each of these HITs should have no more than 9 people. But I am seeing more than 9 workers in each HIT. Also, for at least one HIT I see duplicate assignment IDs. I believe this is because workers can start a HIT and then return it. We'll still keep their data, but they allowed another worker to accept the HIT (which perhaps overloads an assignment ID?). I don't think we have access to whether a worker returns a HIT, but they aren't really "in progress" anymore.

Otherwise, this is fantastic! When we start recording start time/HIT expiration time (and maybe last seen?), it'd be great to include those.

See below about the oddity I mentioned:
![screenshot from 2016-05-06 12 02 01](https://cloud.githubusercontent.com/assets/9325440/15083513/82e0a164-1382-11e6-8f65-660d0f5c3744.png)

**Comment by vsoch** [comment]
In progress just means we don't have any indication what stage they are in, and this is an artifact of the fact that the variable to record accept_time wasn't added until recently - likely some of those workers wouold have appeared in the "ATTENTION" tab if we had their accept_time (this tab is not shown because we don't have any that need attention).

**Comment by vsoch** [comment]
I am not privy to how MTurk uses assignment IDs / worker ids. I can tell you with certainty those are the combinations that we have in the database, resulting from a worker accepting with a particular assignment id. If there is some strangeness (duplicate, etc) it's not something on expfactory end, and if you are concerned I would suggest looking into it.

**Comment by IanEisenberg** [comment]
So "attention" is flagged after their allotted time elapses? It's just a
shame that we can't differentiate those who haven't yet submitted from
those who have returned the HIT (and thus given up). That's on mturk, not
expfactory. "Last seen" will give some indication of which it might be.

The duplicate assignment IDs are only for the "in progress people" who I
believe are not actually "in progress" but actually returned the HIT and
started again. It's not something to do anything about, but it does let us
know that we can't be sure we are uniquely indexing a worker by assignment
ID (because they are not removed from our database if a worker returns a
HIT).

On Fri, May 6, 2016 at 12:24 PM, Vanessa Sochat <notifications@github.com>
wrote:

> In progress just means we don't have any indication what stage they are
> in, and this is an artifact of the fact that the variable to record
> accept_time wasn't added until recently - likely some of those workers
> wouold have appeared in the "ATTENTION" tab if we had their accept_time
> (this tab is not shown because we don't have any that need attention).
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-docker/issues/142#issuecomment-217536314>
>



-- 
Best,
Ian

**Comment by vsoch** [comment]
As I said, this is only an issue with the workers that started before I added the accept_time variable to the assignment. Yes, the "in progress" people could have completed and we have no record. The assignment IDs are unique, as are the worker IDs - it's MTurk that determines these variables when they accept a HIT, and it's not logical to say "we can't be sure we are uniquely indexing a worker by assignment ID" because of course a worker can have multiple assignment IDs.

Attention is flagged when the accept_time + duration of battery has passed, but the assignment still does not have a status.

**Comment by IanEisenberg** [comment]
Of course a worker can have multiple assignment IDs - but there is one assignment ID with two workers:

![screenshot from 2016-05-06 12 38 28](https://cloud.githubusercontent.com/assets/9325440/15084299/7556b7c2-1387-11e6-8e52-db750b4e0441.png)

I was just saying this likely happens when a worker starts the HIT, returns it (so gives up on it) and another worker accepts it. I'm not suggesting we do anything about it, just mentioning it.
