### ISSUE TITLE
Button errors on expfactory.org

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#44]
Errors with button on expfactory.org

Delete_Button:
![delete_battery_error](https://cloud.githubusercontent.com/assets/9325440/13582571/e2c1c7e8-e461-11e5-9d43-088f22524f4d.png)

New HIT:
![new_hit](https://cloud.githubusercontent.com/assets/9325440/13582572/e2c91340-e461-11e5-8291-d7854e8c3532.png)

Batch HIT:
![batch_hit](https://cloud.githubusercontent.com/assets/9325440/13582570/e2c057fa-e461-11e5-9560-1f5d2c69d852.png)

**Comment by vsoch** [comment]
The Integrity error means that you cannot delete an experiment from the infrastructure if it is being used for a battery. If you want to delete an experiment, it cannot be contained in a battery / used for a HIT. The HIT resulted from a partial deletion of an experiment, and in this case you need to remove those experiments from your batteries, and then tell me the names. I will manually remove the templates from the database along with the files, and then you can re-install. These aren't errors that a user would normally see because only the super user admin (who before was just me) would do the process of update/ delete carefully.

**Comment by IanEisenberg** [comment]
The delete is "battery delete" not "experiment delete"

**Comment by vsoch** [comment]
ah, I see. Let's discuss this - do you think a researcher should be able to delete a battery if there is a result for it in the database? This integrity error prevents that.

**Comment by IanEisenberg** [comment]
Yeah, I'm not sure. Right now we have made test batteries (as others will do), and data or no they are just taking up space here. Before I can response to how delete should work, let me ask something else:

Let's say I have collected data, as I have, for a battery that exists - the self regulation battery. But now I want to update the experiments and add experiments to this battery. Really, the battery is no longer the same thing. When I collect new data, is it tagged as the same battery? Even if it isn't (let's say each change of a battery creates a new unique battery ID), how will I differentiate between the two IDs if I were to export results?

**Comment by vsoch** [comment]
Correct - collecting new data gets tagged as the same battery, and it's for this reason there are constraints on deleting. The idea is that when we deploy, updating an experiment would not be something we would do with any regular frequency. This is exactly the reason to have different versions of things, but this perhaps doesn't really make sense to do if the interface isn't offered / publicly available.

My suggestion would be to, when all the experiments are "at their best," add a "version" variable. We would then require that any update to an experiment, no matter how trivial, coincides with updating the version. This way, all versions of experiments would be saved on the server, and there would never be the case of deleting a version when you update. I've avoided this so far because there have been enormous changes to the experiments, and it would be a huge hassle, especially given a test in continuous integration to assert that the version has been updated :)

**Comment by IanEisenberg** [comment]
Yeah, I agree that there should be a difference between "in the future" and now in this tumultuous state. I think you're right - versioning of even trivial changes makes sense going forward, but for now (and this can be manually done by a superuser like yourself) it probably makes sense to just delete things
