### ISSUE TITLE
Remove "Start Experiments" Button in the preview.

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#52]
Additionally, it probably makes sense to end the preview with an "Accept HIT" button rather than "Start Experiments"

**Comment by vsoch** [comment]
We want the preview to mimic the experiment, so removing the Start Experiment button is not ideal in my mind. Instead, I added a view in the background that encourages participation:

![image](https://cloud.githubusercontent.com/assets/814322/13709325/2404b414-e768-11e5-8936-7850e6b04334.png)

The view is present (behind the ad and consent) so that it shows even if the user tries some kind of funny business to remove the Ad / consent modal without clicking Start Experiment.
