### ISSUE TITLE
When a worker accepts a HIT, a new tab should open

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#55]
Right now when a worker accepts a HIT, the HIT is shown in the mturk box. Clicking on "full screen" doesn't do anything either. The way I've normally seen it done is accepting a HIT opens a new tab (or something like that...not exactly sure). It may actually be that other people set it up such that once the worker accepts a HIT, they then press "start the experiment" in the mturk box, which _then_ opens a new tab.

Regardless, there just needs to be some solution that allows the HIT to enter into fullscreen.

Correcting my confused previous issue - we probably want "Start Experiment" to be disabled (or removed) in preview mode. So instead of bringing the worker to a blank preview screen, it just does nothing.

**Comment by vsoch** [comment]
I'm not familiar with how turkers normally do these experiments - within the iframe in amazon? In the "real" (non sandbox) version does it not provide the URL itself as a link? (always an iframe?)

**Comment by IanEisenberg** [comment]
The iframe is the mturk window? I'm not sure what the 'real' version of mturk does - but it should act exactly like the sandbox.

I believe most psychology experiments work by opening up a separate window. At the end of the experiment, data is sent back to mturk to either record the data (not necessary for us) or flag the completion of the HIT.

Right now, the expeirments are contained to that iFrame, cannot go into full screen, and are generally not immersive. So we need some way to allow the experiment to open.

As an example, below is my preview.html code that I used for an mturk experiment. You can see that it checks whether the page is in "preview" mode and if not opens a new window when the participant presses enter. We can do the same thing with a "Start experiment" button (or continue experiment) within the HIT:

[https://github.com/IanEisenberg/Otto_etal_2014_Replication/blob/master/preview.html](url)

**Comment by vsoch** [comment]
Opening a new page with JavaScript is a trivial thing to do. The issue is that the "start experiment" button doesn't open a new page, it just hides the instructions modal. This is a significant change that would require restructuring of the entire deployment, and I'm not sure how to proceed. Minimally I want to verify the functionality of being a Turker, so I'm waiting for my Amazon payments account to be approved so I can see this experience.

**Comment by IanEisenberg** [comment]
I see. I'm sure that a real turker will operate exactly like a worker on
the sandbox (you can log in to the worker sandbox with the same credentials
I gave you to check it out like that). I understand wanting to confirm "for
real" before undertaking a significant restructuring, but I am (almost)
completely confident that the problems/functionality that exist in the
sandbox will exist on mturk itself.



On Fri, Mar 11, 2016 at 3:57 PM, Vanessa Sochat <notifications@github.com>
wrote:

> Opening a new page with JavaScript is a trivial thing to do. The issue is
> that the "start experiment" button doesn't open a new page, it just hides
> the instructions modal. This is a significant change that would require
> restructuring of the entire deployment, and I'm not sure how to proceed.
> Minimally I want to verify the functionality of being a Turker, so I'm
> waiting for my Amazon payments account to be approved so I can see this
> experience.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-docker/issues/55#issuecomment-195607390>
> .
>



-- 
Best,
Ian

**Comment by YingYu26** [comment]
"Right now when a worker accepts a HIT, the HIT is shown in the mturk box. Clicking on "full screen" doesn't do anything either." It happens to me too in 2020! I know this problem was raised 4 years ago. Any solution?

**Comment by vsoch** [comment]
I wish I could offer help, but I’m not part of the lab and don’t maintain this anymore. I think your best bit is to ping @rwblair. Good luck!

**Comment by YingYu26** [comment]
Thank you very much for the reply though! @vsoch 
I'll try to contact him!

**Comment by vsoch** [comment]
Sure thing! If you don’t have any luck please reach out to me so I can contact him to ask about the status of the project. If he is no longer maintaining it then I will likely want to take over again.

**Comment by YingYu26** [comment]
Thank you so much!!! As a researcher in human visual perception, I really need my HIT to run in fullscreen (or immersive) mode, so that the participant can only see my stimulus and no others. I used javascript and integrate it with MTurk. The fullscreen command works well when I *preview* my batch on MTurk. But after I published the batch and do it through worker sandbox, the fullscreen function did nothing while everything else works well, so everything will only be played within the MTurk window (or iframe?) with all the browser tabs and other things visible and users can move and resize the browser window, which is not ideal for my purpose. 
It would be wonderful if this problem can be solved.

**Comment by rwblair** [comment]
@YingYu91 Are you using expfactory-docker to serve these experiments or some other set of software?

**Comment by kolydic** [comment]
@YingYu91 have you resolved this issue? I am facing the exact same problem and desperately need a solution fast! My preview on sandbox allows fullscreen, but when I publish, full screen command does nothing.. what was your work-around? Thanks!
