### ISSUE TITLE
Problems with data file generated

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#57]
Not sure if this is an issue with the data itself or the way the data is downloaded. Regardless, when I clock "export data" from expfactory.org there are a number of issues:

(For this example I completed three tasks: perceptual metacognition, choice (which I think discarded by clicking "redo", and probabilistic selection)

(1) all "experiment" columns are blank. experiment_include_bonus, experiment_exp_id, etc.
(2) battery_completed is true, even though I haven't completed the battery.
(3) results problems. The results from the two tasks that should have been recorded (perceptual metacognition and probabilistic selection) have problems. It seems that the probabilistic selection task wrote over some of the cells for the first task, and didn't record in other places. The mixing of the two datasets is a bit confusing, so not sure what's going on there.

**Comment by vsoch** [comment]
1) The root of this problem is that the exp_id  is not being saved with the results, as it was before. 
2) This is just an incorrect naming of the column - there is no way a battery can be completed (it is for multiple users!) and this variable is for completion of the experiment. So what you are seeing are results for one completed experiment, and the info about the experiment is missing because there is no exp_id in the data to look up those missing columns.
3) I unfortunately can't debug this if the data doesn't have exp_ids. What I can try to do is rewrite the result parsing function to not derive it from the data... not sure if this will work but given the modular infrastructure, it seems like a good idea (the code to parse from the result data itself was done when a battery was one long thing). Regardless, the exp_id needs to live with the data, because export outside of expfactory.org means that the result is not labeled. Let me know when you've fixed this and the experiments can be updated, and test the export again.

**Comment by vsoch** [comment]
Export is fixed. I've created another issue https://github.com/expfactory/expfactory-experiments/issues/405 to address the exp_Id variable not being present in the results data.
